name: Create Issue Template

on:
  workflow_dispatch:
  
jobs:
  create-issue-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create issue template directory
      run: mkdir -p .github/ISSUE_TEMPLATE

    - name: Create bug report issue template
      run: |
        echo "# Bug Report
        ## Description
        A clear and concise description of what the bug is.
        ## Steps to Reproduce
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
        ## Expected Behavior
        A clear and concise description of what you expected to happen.
        ## Screenshots
        If applicable, add screenshots to help explain your problem.
        ## Environment
        - OS: [e.g. macOS, Windows]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
        ## Additional Context
        Add any other context about the problem here." > .github/ISSUE_TEMPLATE/bug_report.md

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .github/ISSUE_TEMPLATE/bug_report.md
        git commit -m "Add bug report issue template via GitHub Actions"
        git push
